- name: Install dependencies
  apt:
    name={{ item }}
    state=present
    update_cache=yes
    cache_valid_time=3600
  with_items:
    - python-meld3
  sudo: yes

- name: Download supervisor package
  raw: find /tmp/{{ supervisor_deb_file }} || wget https://launchpad.net/ubuntu/+archive/primary/+files/{{ supervisor_deb_file }} -O /tmp/{{ supervisor_deb_file }}
  sudo: yes

- name: Install supervisor package
  apt: deb=/tmp/{{ supervisor_deb_file }} state=present
  sudo: yes

- name: Ensure backwards compatibility for config location
  file:
    src=/etc/supervisor/supervisord.conf
    dest=/etc/supervisord.conf
    state=link
  sudo: yes

- name: Installing task {{ name }}
  template: src=task.conf.j2 dest={{ supervisor_config_dir }}/{{ name }}.conf
  sudo: yes

- name: Update supervisor
  command: "{{ supervisorctl_command }} update"
  sudo: yes

- name: Restart task {{ name }}
  command: "{{ supervisorctl_command }} restart {{ name }}:*"
  sudo: yes
